# Contains the system prompt and few-shot examples for training scenario generation.


# System prompt for LLM
instruction_prompt = """
Persona: You are an Expert Air Traffic Management (ATM) Training Specialist and Subject Matter Expert (SME) with decades of experience designing high-fidelity simulation scripts for the FAA and international civil aviation authorities. 
Your specialty is drawing upon your expertise to design realistic training scenario of varying complexity that incorporates complex, mathematically rigorous traffic and weather data.

Task: Your task is to generate a training script that exposes ATM trainees to real-world disruptive scenarios based on specific quantitative parameters.

Constraint - Data Integrity: You will be provided with quantitative parameters (Weather features, TAF/METAR, Airport Arrival Rates). These are generated by a stochastic optimization model and are technically rigorous. You must treat this data as "Ground Truth"—Incorporate all quantitative parameters exactly as provided, without commentary.
If you are not provided with weather data, generate your own realistic weather data that would fit into the scenario you are generating.

Script Structure:

Background/Scenario Setup: Establish the operational context (shift time, facility, and current weather/METAR data).

Assessment Question: A prompt asking the trainee to identify which airport(s) or sectors will face capacity issues based on the provided background.

Stakeholder Dialogue: Continued prompt/expected answer pairs using "agents" (e.g., Tower Controller, Flow Lead, Airline Dispatch, Center Supervisor). The dialogue must reflect professional ATM phraseology and perspectives.

Instructions:

Style & Tone: Match the technical precision, urgency, and professional tone of the provided examples.

Creative Filling: If the user's prompt for the scenario to generate is vague, use your expertise as a Training SME to fill in logical details that align with the provided quantitative data.

Weather Integration: Do not list the weather as a table. Instead, weave it into the "Background" and "Agent Dialogue" (e.g., "We're seeing a ceiling drop at Newark that's going to hit our arrival rate by 1400Z").

Originality: Follow the structure of the examples provided, but generate a unique scenario that leverages the specific disruptions indicated by the data.
The generated script must read as an in-universe training product.
Do not reference: instructions, constraints, ground truth data, prompts, examples, stochastic models, or generation rules.
Any language that explains how or why the scenario was constructed is prohibited.
The output must appear fully handwritten by a human ATM training SME.
"""

semantic_parsing_instruction = "Format the training script in markdown with section headers, bold, etc. Do not include the word markdown in the training script. Between ``` and ``` demarkers, give me a training script for the following prompt:" 
query_template = semantic_parsing_instruction + """ {nl_query}

Training script: 
```
{sql_query}
```"""

few_shot_examples = [
     ("""
     Generate a Level 1 terminal training scenario for San Francisco International Airport (SFO). 
     The scenario should begin at 1030 UTC and focus on evolving weather conditions: low ceilings filling in within a few hours and a wind shift to the southeast (190@10G15) between 14-15Z. 
     The simulation must include a disagreement during the Ground Delay Program (GDP) telcon: ZOA and the TRACON should advocate for an early 14Z start at a 28 rate to avoid holding, 
     while United Airlines (UAL) should push for a 15Z start based on their own weather forecast. Provide specific TAF/METAR sequences and scripted dialogue for the instructor and facility representatives.
     """, 
"""
Training script:
The scenario will start with the student assuming the position for training at 1030UTC. They will be given the TAF/METAR for the Terminal West Position Airports and have access to the FSM and TSD.
After the student evaluates issues at their position the instructor will ask…
Instructor: What airports do you expect will see issues for the shift today?
The only airport needing attention will be SFO.
The weather Specialist delivers the 11Z weather sheets and gives you the following briefing.
Weather Specialist: Low ceilings will begin to fill in over SFO sometime in the next couple of hours. Currently, winds are calm, but expect the winds to pick up from the SE between 14 -15Z. Winds are expected to be 190@10G15. Low ceilings may scatter out around 20Z when the winds are forecasted to shift and blow out of the west. (TAF should still show cloud layers through 23Z) Rain is forecasted through 19Z and we should get to VFR by 23 – 00Z.

Here is what the weather sequence for today:
KSFO 170852Z 1709/1812 19009KT P6SM VCSH BKN025 OVC040
     FM171300 14009KT P6SM -SHRA BKN020 OVC035
       TEMPO 1713/1717 4SM -RA BKN015 OVC025
     FM171800 23014G20KT VCSH SCT015 BKN025 OVC035
     FM172300 26012KT P6SM VCSH P6SM FEW025 SCT035
     FM180600 25016G22KT P6SM -SHRA BKN025 OVC035
 

Student should be given opportunity to use all TM tools available to determine a course of action.
Instructor: What are your ideas regarding SFO?
Options: Wait or SFO will need a Ground Delay Program.
		
•	If GDP  
o	Instructor: Can you model an SFO GDP based on the weather sequence provided by DCC weather?
Instructor: That’s a good starting point. What are you going to do next?
Options:  Wait, Talk to UAL Weather, or hold a SFO GDP Telcon. 
Here is the Updated SFO WX from DCC WX Unit:
KSFO 171148Z 1712/1818 19009KT P6SM VCSH BKN025 OVC040
     FM171300 14009KT P6SM -RA BKN015 OVC025
     FM171800 23014G20KT VCSH SCT015 BKN025 OVC035
     FM172300 26012KT P6SM VCSH P6SM FEW025 SCT035
     FM180600 25016G22KT P6SM -SHRA BKN025 OVC035

Some trainers will teach to hold a telcon with FAA facilities only first, and some will teach to hold the full telcon. Here is what each element will say regardless of when they speak to them. 
ZOA WX – Low ceilings will be in place by 1430 – 1445Z winds will be out of the SE through 20 – 21Z, then expect a shift to westerly winds. Rain showers are expected through 20Z. Clouds will decrease by 20Z, but don’t expect VFR conditions until 2330 or possibly 00Z. 
UAL WX – We don’t see the ceilings coming in until 1500Z. We do see the wind shift occurring around 20Z and the possibility of VFR ceilings at that time. 
SFO – Right now we are in a West Configuration. 28 Left will be back by 14Z. We expect to be in a SE configuration, arriving 19L and departing both 10L/R as the winds start to blow out of the SE. If the winds do shift to the West as forecasted, we will be able to move to a 28/10 operation. 
NCT – Right now we are at a 40 rate. When we shift to a SE configuration, we will be at a 28 rate and will stay there until we are able to get to a West configuration.  When in West configuration, we will be at a 36 rate until we get to VFR conditions and can raise the rate to 40. I’m concerned with the timing of the IFR ceilings.  When this happens we will need to shift operations and go to a 28 rate. I suggest we be cautious and plan to be at the 28 rate by 14Z to avoid holding. It will be better for the operation if we get to a 19/10 Operation prior to the start of the GDP rather than during. 
ZOA – We agree with the TRACON. We would like to see the program start at 14Z at a 28 rate to avoid a holding and possible Ground Stop.
UAL – According to my weather people, the ceilings will not be an issue until 15Z at least. How confident are you about that?  
UAL WX – The ceilings are moving west at 20 kts. I have medium confidence on the forecast. If the winds pick up earlier, it could move the ceilings in sooner.  
UAL – I think we could wait to start any program until 15Z but understand starting at 1400Z. 
DAL – We will defer to UAL on this. 
ASA – We disagree. We do not want to see any holding, Ground Stops or Metering. We think we should start the program at 14Z at the 28 rate.  
Instructor – Why do you think ASA feels this way? (Most of ASA fleet comes from SFO to the first tier, so they have the most to lose if SFO goes into a Ground Stop or has to meter on top of the GDP.)

The student will need to take all this information into account and decide how to precede. 
Options: Go with facilities recommendation or UAL’s recommendation. 
If student asks DCC weather for an updated forecast, DCC weather will support the ZOA WX’s forecast. 
Student will then model their SFO GDP. (Remember, this will be a long GDP and the student should expect some cancelations. They should run the GDP with a stack to account for cancelations and reduce the Average Delay.) After they have finished modeling their program, Instructor should ask the student the Pros and Cons of each option and what led to their decision. 
Student will then send out the SFO GDP Proposal. 
The student will hold the GDP telcon when stated on the proposal. We want to see if the student can explain and defend their position on why they decided to propose the GDP they did. We want to object as the opposite side to the proposal. If the student sides with the facilities, UAL should say they are taking unnecessary delay by starting the program an hour early. If the student goes with UAL’s proposal, then TRACON and Center, as well as Alaska, should chime in saying that the risk of a Ground Stop and revision is too great to start the GDP when UAL wants. 
After the telcon, student will send out the GDP and make the correct calls to notify the Centers.
"""
),
     ("""
     Create a Level 3 terminal training scenario for Chicago O'Hare (ORD) starting at 1030 UTC. 
     The primary disruption should be thunderstorms forming northwest of the airport and moving east, impacting arrival/departure gates by 17Z. 
     The scenario should require the student to manage a transition from a 114 rate to a posture where storms shut down the airport. 
     There should be uncertainty in how the weather materializes, and the student should be provided from a range of traffic management initiatives to make a decision given the information that is present at the time. 
     Include a conflict where ZAU expresses concern about gate blockages while C90 wants to stay 'wide open' as long as possible. 
     Script the telcon to include airline requests for lower rates (e.g., 56) to limit diversions.
     """, 
"""
Training script:
The scenario will start with the student assuming the position for training at 1030UTC. They will be given the TAF/METAR for the Terminal West Position Airports and have access to the FSM and TSD.  
Once they’ve had a chance to evaluate issues at their position, the instructor will ask:
Instructor Question: What airports do you expect will see issues for the shift today?
	***The only airport that will need attention will be ORD.*** 
The DCC weather person comes over to drop off the 11Z weather sheets and gives you the following briefing:
Thunderstorms will form NW of ORD and proceed toward the airport. The storms are forecasted to arrive at ORD sometime in the 17Z hour. They should be clear of the area by 1930 – 2000Z. Gusty winds could cause issues from 17 – 20Z.
Here is the weather sequence for today:
KORD 
FM181500 30008KT 6SM SHRA VCTS BKN050CB 
     FM 181700 27020G30KT 2SM TSRA SCT010 OVC020CB 
     FM182000 18009KT P6SM SCT020 BKN035 
     FM182200 15014G15KT P6SM SCT040
     
Show ORD FSM Chart here:
Student should be given the opportunity to use all TM tools available to determine a course of action.
Instructor: What are your ideas regarding ORD?
Options: According to forecast, ORD will need an initiative later.
•	If GDP:  
o	Instructor: Can you model an ORD GDP based on the weather sequence provided by DCC weather?
Instructor: That’s a good starting point. What are you going to do next?
Options: Wait, Talk to UAL Weather. 
•	If student chooses to talk to UAL WX: 
o	Frontal boundary with thunderstorms are forecasted to form west of ORD and move eastward. They will affect C90 and ORD airspace sometime around 17Z. Gusty winds will also be present until 19Z.

***If the student has UAL on the line they will say:*** 
UAL – We are concerned with the thunderstorms at the field today. We do not want to get in a posture where we have a lot of diversions. We would prefer to slow things down prior to the potential impact at the field to limit diversions. 
1319Z – ZAU calls DCC:
ZAU – Our weather staff says that thunderstorms will begin to form in our western airspace and move east toward ORD. We think these storms will impact our arrival/departure gates on the west side. When that happens, we will not be able to deliver the rate to the TRACON. I think we should bring everyone up and discuss a GDP beginning at 15Z.
Here is a screenshot of the weather in ZAU at 14Z:
Options: Hold a telcon to discuss the potential thunderstorm impacts or wait until there is some thunderstorm formation within ZAU.
•	If student chooses to hold telcon:
ORD – Right now things are good. We are on a west flow with a 114 rate. We expect to hold this rate until the forecasted storms enter TRACON airspace. We expect to initiate an east flow operation as the front moves across the field. 
C90 – I agree with ORD, 114 rate until the storms come through. I think we will then be dropping to something around 76, but that all depends. If the storms move over the field, we could lose the airport entirely until they are clear.
ZAU – Our concern is that when these storms form, they could close off both our west gates for arrivals and departures. We would only be able to arrive and depart from the east gates and would only be able to feed about 76 arrivals per hour. I have seen this happen many times before and we wind up holding a bunch of aircraft with lots of diversions. I recommend we slow the arrivals down beginning at 15Z. Maybe 88 in the first hour then 76 in the 16Z hour. We can always release 1st tiers if we have room. By 17Z, the storms are forecasted to be in TRACON airspace and we will need a program anyway.
C90 – We will not need a GDP at 15Z. We will still be at a 114 rate wide open. We don’t need to limit arrivals at that time. The storms might not even go over the field.
ZAU – That’s true but we will not be able to get the aircraft to you if our gates are blocked. 
•	If the student brings in the Airlines: 
UAL – We support ZAU and would like to see a much lower rate during the 17Z and later time when the storms will impact the airport. I think a 56 rate will keep us out of Ground Stops and limit diversions.
AAL – We do not agree with the 56 rate. That is just too low. (***If asked they would request 76 rate during the impact times***)

Options: Work up a GDP or wait until the weather forms.
•	If Student choose a GDP, there are several options to work through.  
A.	ZAU/UAL requests – beginning 15Z    88/76/56/56/56/76/76/88/114
B.	ZAU/AAL requests – beginning 15Z    88/76/76/76/76/76/76/88/114
C.	Compromise 

•	Or, they may choose to wait for thunderstorms to develop.

1500Z weather update:
 ORD 181500 20008KT 6SM SHRA VCTS BKN050CB
     FM 181700 30020G30KT 2SM TSRA SCT010 OVC020CB 
     FM182000 18009KT P6SM SCT020 BKN035  
     PROB30 1821/1901 -TSRA BKN040CB


By 1500Z the storms have begun to form and are beginning to intensify moving eastbound. There is an added PROB30 of –TSRA between 21 and 01Z.

Show screen shot here:


•	If student chooses not to issue a GDP to help ZAU:

1515 Planning Telcon:  

ZAU – The thunderstorms are affecting our arrival and departure routes. We are in SWAP now taking all departures out the east gates. We are going to need to do something for the arrivals. They are deviating and are not going to be able to get into the west arrival gate soon. We need a GS ASAP.

Planner – The west specialist will hold a side bar right after this call.

ZAU – Make it fast!!!!

Student should be working up a GS (1st tier) then expect to go into a GDP out of the Ground Stop with the conference the same as above except the addition of the PROB 30 from 19 – 01Z. UAL thinks that the rate should take that into account and not jump to 114. They feel that the rate should stay at 88 until 00Z. ZAU and C90 disagree and support the previous plan.

1600Z  - 15Z Counts
	Path A   88/75
              Path B   40/75      ZAU +15 A/D 1540Z

1700Z  - 16Z Counts
	Path A    74/62
              Path B    81/59     ZAU +30 A/D 1602,   ZAU – 30 A/D 1629


1721Z – C90 asks DCC to bring up ORD and ZAU to discuss the thunderstorms.
     
C90 – We expect the storms to begin to affect the finals around 1730 and to shut down the airport before 18Z. We should discuss a Ground Stop. The airport could be shut down for over an hour. 

ZAU – I agree. We need to stop arrivals to limit diversions until the airport is able to reopen.

UAL & AAL – Agreed. 

***Student should now be working up a Ground Stop that will limit traffic to the airport for at least an hour. They will need to decide if a 1st tier GS will be sufficient, then implement the GS. (For both Plan A and Plan B)***

***Next they should be looking at a GDP out of the Ground Stop. They should be holding a telcon to determine the rates and time to implement GDP revision.***

1732Z – ORD +15 D/D,   1747Z -  +30  D/D ,  1802Z - +45 D/D

1735Z – ZAU +30 A/D,    1750Z  +45 A/D 
 

1800Z – 17Z counts 20/21

***Student should be calling facilities by 1800Z to see if the GS needs to be extended.***

Facilities agree the GS should be extended and, if asked, they agree to drop the scope to a 1st tier because the storm should be off the airport within about 20 – 30 minutes.  
If they do not ask, the instructor should ask the student if they think a reduced scope would help since the storms are going to be off the field within 20 minutes or so.

Instructor should make sure the student issues the GS extension properly and makes the correct phone calls releasing the 2nd tier Centers and extending the 1st tier Centers.  

***Next, the student should be working on a GDP revision.***
1805Z – ZAU A/D -45 and -30.

GDP revision telcon:
 
***DCC Student should initiate a telcon with facilities and users about GDP revision out of Ground Stop.***

ORD – Storm looks like it will be moving away from the field shortly. We are still +45 Departure Delays and we need to get the surface cleaned up. Whatever you wind up doing, we need to get departures out!

C90 – When the storm passes, the east gates will be closed to arrivals and departures for a couple of hours. I would say when we come out of the ground stop we run one hour at a 56, then we can raise the rate to an 86 for an hour, then a 114 unless the second round of storms hit the field.

ZAU – I agree. We will be coming out of the stop soon. Command Center, I think you can cancel the Ground Stop as soon at the TRACON begins to take traffic. I’m good with the 56 rate then the 86 rate, but I would put the next hour at 96 before jumping to a 114 rate. The last briefing I got from Center weather was that the second wave of storms are not going to affect ORD.

ZAU WX – Agrees with ZAU assessment.

UAL – I like coming out of the Ground Stop as soon as possible, but my weather folks still think the second wave of thunderstorms has a 30 percent chance of hitting the field. I think we should set the rates of the GDP accordingly. I also think jumping from a 56 to an 86 is too much. We would like to see a 56/76/76/86/86/86/114. That will take into account the second round of thunderstorms over the field and keep us out of another Ground Stop.

UAL WX – We are still carrying the PROB 30 at ORD for thunderstorms after 21Z, but we do not think they will last longer than 23Z.

AAL – We would like to see a program that will keep us out of another Ground Stop.

***The Student will then need to decide at what program rates to run the GDP revision.***

•	If they ask DCC weather, they would say:
  
DCC WX – We don’t think the second round of thunderstorms are going to develop. We are thinking about taking them out of the forecast.

1822Z – ZAU calls DCC: 

ZAU – TRACON has started taking arrivals. You can cancel the Ground Stop and initiate the revision.

***Student should then cancel the GS and initiate the revision. Instructor will guarantee the student does the procedures correctly and completes the notification calls.***

1839Z – ORD -45 D/Ds

1852Z – ZAU out of A/Ds

1854Z – ORD -30 D/Ds

1900Z – 18Z counts – 39/60

2000z – 19Z counts – 76/74

2009Z – ZAU calls DCC and says:  

ZAU – Let’s bring everyone up, looks like things are improving rapidly. I think we can raise the rate on the GDP.

***DCC Student should then call the facilities to discuss raising the rates.***

ORD – Things are looking much better. The surface has cleared up, as has the weather. We should be out of delays within the next 15 – 20 minutes. 

C90 – Yes, we are doing much better. I think we can take more traffic. We have been releasing some local airports. I think we can do 96 this hour, then 114 for the rest of the program. I don’t see any additional weather being a factor.

ZAU – I agree with the TRACON. We can give them whatever they can accept. We are going to release the 1st tiers to get them more aircraft.

UAL and AAL – Yes, the weather kind of fizzled. Let’s get these revisions and get aircraft moving.  

***Student should revise the GDP with a 96 rate in the 20Z hour then 114 for the remainder of the program. After making revisions, the student should send out the program and make all the calls.***

END OF SIMULATION
"""
),

     ("""
     Generate a Level 3 terminal scenario for LaGuardia (LGA) starting at 1000 UTC. 
     The scenario must involve multiple concurrent issues: low ceilings, gusty winds causing compression by 12Z, PROB30 thunderstorms between 17-19Z, and a mandatory runway change to RY13 operations late in the day (22-01Z). 
     The student should choose from multiple options for responding; either modeling a GDP to change rates as the thunderstorm materializes, or adopt a wait and see approach and groundstop into a GDP if the weather materialized. 
     Ultimately, a low rate (20-rate capacity during the runway change) will be required. Include coordination scripts for N90 and instructions for managing impacts on Teterboro (TEB) arrivals.
     """, 
"""
Training script:
LGA Weather Scenario

The scenario will start with the student assuming the position for training at 1000 UTC. They will be given the TAF/METAR for the Terminal East Position Airports and have access to the FSM and TSD.  
Once they have a chance to evaluate issues at their position… 
Instructor Question: What airports do you expect will see issues for the shift today? 
***LGA is the only airport that will need attention.*** 
The DCC weather person comes over to drop off the 11Z weather sheets and gives the following briefing:
Low ceilings with gusty winds and thunderstorms forecasted for LGA today. Currently, the winds are calm but expect winds to pick up as the day goes on. Strong winds are forecast from 2000 – 5000 feet. Winds will shift to a Southeast flow {use data} later in the day. 
Here is the weather sequence for today:
KLGA   260952 19004KT 10SM BKN050 BKN250 22/13 A2997 RMK A02 SLP142 T02220133
KLGA   261100Z 2610/2712 19005KT P6SM BKN060   
            TEMPO 2612/2615 18015G25KT 5SM BKN 050CB
             FM261500 16011G34KT 2SM BKN015 PROB30 2617/2619 1SM –TSRA BKN005CB
             FM262200 13015G25KT 1SM BKN020 
             FM270100 12008KT 6SM BKN120            

LGA FSM SHOT Here:

Student should be given the opportunity to use all TM tools available to determine a course of action.
Instructor: Look at the weather for the East airports. Determine if there are any that need your attention. If there are, rank which ones will need attention first, then determine a course of action for each.
***LGA will be the airport that needs attention.*** 
The issues at LGA are as follows:
1.	Gusty winds and compression beginning at 12Z.
2.	PROB30 thunderstorms forecasted between 17 and 19Z.
3.	Runway change to RY13 Operation forecasted from 22 – 01Z.
***Student should be given a few minutes to develop/model any initiatives he/she feels might be necessary for LGA.***
After given enough time to work on a plan, the student receives a call from N90. 
Good Morning, looks like LGA is in for a very busy day according to the forecast. Right now things are okay, but we are looking at some gusty wind with compression issues beginning in 90 minutes or so followed by thunderstorms and then possibly a wind shift to a SE configuration. The compression will affect our arrivals for sure. Have you looked into anything yet? We are thinking a 32 rate for the compression. If these thunderstorms materialize, they will affect arrivals/departures on the West gates first and then maybe shut down the field. Do you want to work something up and get back to me?
***Student may have something worked up or will call N90 back after setting up any initiatives they might deem necessary.***
Options: (Path A) Model a GDP at rates they deem correct. They could change the rates to reflect the thunderstorms as well as the SE flow, or set a rate that will address the compression and wait to see if the storms and the SE flow develops.
(Path B) Since this is a weather forecast, they could wait and Ground Stop into a GDP if/when the winds materialize. 
***Both paths lead to a telcon with the facilities and users.*** 
***Some trainers will teach to hold a telcon with FAA facilities only first (I taught this way), and some will teach to hold the full telcon. Here is what each element will say regardless of when they speak to them.*** 
N90 – As we discussed earlier, the forecast calls for gusty winds, compression and thunderstorms. We think we should be at a 32 rate for the compression and lower for the thunderstorms if they impact the arrival/departure gates. We could be shut down if the storms go over the field. 
LGA – I’m concerned about the surface. I was briefed that compression will be a major factor and I don’t want to see the airport back up and go into possible gridlock. TRACON, are you sure a 32 rate is low enough? Something you did not mention, I’m very concerned about going into an SE operation later this evening. 
DAL – I see that compression could be an issue but I feel we should try to land as many as we can before the winds and compression take effect. I think we should not do anything until the compression becomes an issue. I do not feel that a 32 rate is necessary. If we need a GDP, I think the lowest it should be is a 34 rate. 
AAL – I see Delta’s point. Although I hate to see a Ground Stop with it being a wind issue, it may not arrive at the time it is forecasted. I can support either plan.
UAL or any other Airline called – We defer to what the major airlines would like to do. 
Student will need to decide if they issue a GDP and, if so, at what rate (with DALs objection and their request it be noted) or wait and GS into a GDP when the compression becomes a factor.  
***For either path, the winds do arrive as forecasted at 12Z. If the student choses Path A, the instructor should make sure the GDP was issued correctly, DAL’s objection was noted, and all calls to facilities were completed.***

Arrival/Departure Counts:
10Z    36/15
11Z    35/16
For Path B at 1242Z LGA calls and asks you to bring up N90.  
LGA - They tell you both that the compression is starting to back up departures and that although they are not in departure delays yet, they expect to be at least +30 in the next 20 minutes and it looks like the delays will keep rising if something is not done.  
N90 – I agree, we are having to increase the separation on the arrivals due to the compression.  Command Center, we should Ground Stop now and come out into the GDP at a 32 rate for the added spacing on arrivals and to keep the LGA surface moving. 
LGA – DCC you can show us +15 D/Ds at 1246Z. 

Student should be modeling and issuing a Ground Stop (usually a 1st tier stop works fine due to the number of arrivals that are within the first tier) then model a GDP proposal. 

***Whether they hold a telcon before or after sending the proposal, here is what the stakeholders will say.***
N90 – We agree with the 32 rate. Just one question. You see the thunderstorms in the forecast for 17Z. They could affect routes in and out in a few hours. Do we want to factor that into the account before we send out the Program so we do not have to put out another Ground Stop? 
LGA – I am still concerned with the surface. I am hoping a 32 rate will be good enough. We are now +30 Departure Delays at 1301Z. 
DAL – I still think a 32 rate is too low and as far as the thunderstorms are concerned. They are a PROB30. Right now we don’t know if they will materialize, where they will be, or where they will be heading if they do. We need to wait on any rate changes due to storms! I think a 34 rate coming out of the GS will work.
AAL – I support any rate that does not put us into another Ground Stop. 

Options:  
1.	Ground delay program at a 32 rate 
2.	Ground Delay Program at a 34 rate.
3.	Compromise GDP at a 33 rate.
4.	GDP at one of the above mentioned rates then a lower rate for the possible thunderstorms. 
Instructor will make sure the student has modeled and issued the GDP correctly (Out of Status) and made all the appropriate calls. 
LGA Arrival/Departure Info:
1200Z  34/20
1301Z  LGA +30 Departure Delays
1300Z Path A  31/22
           Path B  21/14
1449Z  LGA +15 Departure Delays
1454Z  For Student who chose a 34 rate GDP – N90 calls and says they have increased the MIT to their first tiers due to the arrival back up. N90 asks DCC to bring up 1st Tiers to tell them of possible holding due to arrival back up. N90 tells DCC that a Ground Stop might be necessary. 
***Student should be looking at a solution to the arrival issue.***
Options:
1.	Ground Stop with a lower rate revision.
2.	GDP Revision with lower rates without a GS (Like a 28 then 32). 
3.	Since storms are forecasted, maybe look at revision when storms begin to affect arrival/departure gates.
1400Z  32/26
1515Z Planning Telcon
ZNY – We are starting to see storms build to the West. We will be increasing our MIT to ZOB for N90 arrivals. We expect to have to increase the MIT for N90 departures due to deviations. 
N90 – The storms are no longer forecasted to transverse the airports but will move through N90 airspace affecting the West Gates first, then the North Gates.
Planner – I will have the East Specialist conduct a sidebar after the telcon.
***The student should be gathering weather information to bring to the telcon in order to make some decisions on possible solutions.*** 
DCC weather – I have conferred with ZNY Center WX and we agree that the storms will grow and intensify. The development has begun in central PA and will be moving quickly NE, just missing the N90 airports, but will still affect N90 airspace. The storms will be most impactful from 18 – 20Z before dying out. 
DCC Supervisor – Severe weather will be routing more aircraft through ZDC until the weather clears the West Gates, then bring the West gate arrivals back on northern routes. As the weather moves NE they will reroute traffic that normally comes through ZBW around the storms to the west if necessary. There may be a time when we will need to stop traffic originating from ZBW. We would like to see a GDP revision that steps the rate down with the low hours of 18 – 20Z, then steps it back up. I know you may get some push back but we need to use our “51%” on this one!  
Student will need to model the GDP requested by the Supervisor before holding a telcon. They will need to decide if a GS is needed prior to implementation. (The student may be able to do a revision beginning with a step down at 16Z or 17Z if they can get it out quickly).
Possible rates of Program:
16Z  32
17Z  30
18 – 20Z  28
21Z  30
22Z  32
***After the Proposal is sent, the student will need to hold a telcon. Here is what the participants will say.*** 
LGA – I agree with these rates. We are about to go +30 D/Ds and it will be climbing. N90 has increased the MIT on West Gate departures.
N90 – We have increased the MIT because the center has increased the MIT to us.  I know we are expecting this weather to really impact the West gates. We were not thinking we need to go to as low as a 28 rate, but we can certainly support the rate. We know ZDC will have trouble getting into the flow if the traffic is rerouted through them, so the lower rate might help them get internals into the flow. We also still have the compression issue and that is not going to go away any time soon. 
DAL – We don’t agree with the rates. We feel they are way too low. We do not need to go to a 28 rate. We would like to see a 32 rate.  
AAL – We would like to stay out of rolling Ground Stops and surface issues. We think a lower rate is necessary but is a 28 rate too low?  
LGA – We are struggling to land 32 right now. With the increase in the MIT on departures, we will have surface issues if we continue to favor arrivals at a rate that is too high for the conditions. 

Before the telcon, the Instructor should discuss how a telcon like this should be conducted. It is a tough process, empathizing with everyone’s concerns but still letting them know the reasons why we need to run the rates we are going to run without looking like we have not considered all options. This is one of the toughest telcons to conduct because the stakeholders usually come away feeling DCC did not collaborate with them. 
Student will then initiate the Ground Stop into GDP revision or just the GDP revision. 
Instructor will make sure the GDP is issued correctly and all calls are made to inform facilities of the changes.  
1537Z  LGA +30 Departure Delays
LGA Arrival/Departure Info:
1500Z  31/28
1600Z  32/22
1700Z  29/24
1800Z  27/21
1858Z – LGA +45 D/D’s
1900Z  26/19
2000Z  27/26
2017Z   LGA -45 D/D’s
2033Z   LGA -30 D/D’s
2100Z  30/26

At 2222Z N90 calls DCC to tell them they need a Ground Stop for LGA. They are switching to a RWY 13 operation.  
Student should discuss what initiatives, and in what order, they need to be implemented.
Instructor should ask the reasons why these initiatives need to be enacted. If necessary, the instructor should show the student the N90 confliction program to ensure the student knows exactly what is happening at the airports. 
The student should issue the following initiatives in order:
1.	1st tier Ground Stop for LGA.
2.	TEB Ground Stop. The student will need to go far enough out to make sure they will be able to come out of the GS into an 8 rate GDP at TEB.
3.	Issue a 20 rate GDP for LGA for the entire time LGA is expected to be in the RWY 13 operation. ***(Since the WX forecast calls for VFR weather with no gusty winds after LGA can come off RWY13 operations, the remaining hours of the program can be run at a 36 rate).***
4.	Issue an 8 rate GDP for TEB for the entire time LGA is expected to be in the RWY 13 operation. 
Instructor should make sure the GSs and GDPs are coordinated with the proper stakeholders and implemented correctly. They should also ensure all coordination has been completed properly. 

LGA Arrival/Departure Info:
2200Z  16/14
2300Z  20/19

At 0038Z N90 calls to inform DCC that LGA will be transitioning to a RWY 04 operation and a 36 rate. 
0000Z  21/22
0100Z  20/19
0200Z  37/28

End of Simulation
"""),

     ("""
     Develop a severe weather scenario for Dallas/Fort Worth (DFW) focusing on convective development in the west at 2030 UTC.
     The weather should impact the VKTRY and JOVEM arrival gates, requiring the student to evaluate fix balancing and move traffic to the SOCKK arrival (southwest gate). 
     The student will be given multiple options for action, spanning from no assistance, to tactical moves, and lastly, a national playbook implementation. 
     The expected outcome is the implementation of the DFW_VKTRY playbook. 
     Include specific meteorologist briefings regarding 'medium coverage' confidence and scripted facility feedback from ZAB and ZLA during the implementation conference.
     """, 
"""
Traning Script:
***Instructor will recall saved FEA to display simulated weather.***

Part I 

The student will assume the position for training at 1030UTC. They will be given the TCF for the scenario. Student is expected to review weather products then obtain a briefing from meteorologist. 

When student asks for Meteorologist briefing: 

The weather system is expected to develop around 21z. I believe it will start earlier, around 2030z, with sparse coverage from LBL to south of INK. ZFW/ZHU meteorologist wanted medium coverage during the weather chat conference for the southern part of the forecast, but I do not see that happening. I am confident we will have medium coverage from TXO to LBL starting around 2130z. The system will continue to develop until 01z. 

After student has evaluated the issues at their position the instructor will ask… 

What type of weather is forecast? 
•	Air mass system? 
•	Frontal system? 
•	Combination of both? 

What is the life cycle? 
•	Speed? **10kt for this scenario** 
•	Direction? **moving northeast** 
•	Duration? **4+hours** 

Will TRANSCON routes be needed? 
•	Explain reasoning? 

Will Regional routes be needed? 
•	Explain reasoning? 

Regional routes into DFW should be the only area of concern. Expected outcome is DFW_VKTRY playbook implementation. TRANSCON between ZLA/ZOA/ZAB to/from 
ZJX/ZMA are sometimes considered, but typical volume does not justify the need for a route. 

Part II 

Allow student to develop strategy for the National Airspace System. Once the student begins to build structured routing, Instructor will ask: 

What arrival gate is being impacted? 
•	VKTRY/JOVEM arrivals 
What major market groups normally fly over the impacted gate? 
•	ZLA/ZOA/ZDV/ZLC/ZSE 

What gate are you going to move the impacted traffic to? 
•	Expect outcome is SOCKK arrival which is SW gate. This is typically a lower volume gate. 
•	If the student wants to move the traffic to BRDJE/WILBR/SEEVR gates (NE Gate), volume becomes an issue. You may have to move the northeast traffic to the south east fix to manage the volume. 

How much volume will be impacted? 
•	For simulation, the volume is 25 aircraft over the impacted time period. 

The Meteorologist delivers the updated briefing: 

The weather system is developing as expected with development starting at 2130z. The northern end should not extend north of LBL with the medium coverage. Some of the forecasting models are showing the medium coverage extending further south to CME. I am not confident of this medium coverage. I think medium coverage will be between CME and TXO. 

Part III 

Student will finalize the strategy to manage weather impacts and develop/park expected routes. 

Instructor should discuss the following: 

Option 1 - No assistance need from DCC: 
•	Conference impacted facility. 
•	Describe the weather system and expectation. 
•	Explain and defend why no assistance is needed. 

Option 2 - Tactical Move only: 
•	Conference impacted facility. 
•	Describe the weather system and expectation. 
•	Explain and defend why Tactical moves will be used. 

Option 3 - National Playbook implementation. 
•	Build and park needed routes. 
•	Conference impacted facility. 
•	Describe the weather system and expectation. 
•	Describe the complete strategy for the day 
•	Explain and defend why National Playbook route will be issued. 
•	Be prepared to provide data to support your decision. 
•	Be prepared with alternate routes to manage possible volume concerns. 

Part IV 

Student will discuss their strategy with instructor. 

Instructor will ask: 

When will the route need to be implemented? Why? 
•	Regional routes are implemented after the weather starts to develop. 

What is the volume during the impacted time frame? 
•	Discuss FEA evaluation 

Student will coordinate their route with field facilities. 

Instructor will look for: 
•	Student to have route parked and shared with facilities. 
•	All impacted facilities to be in the implementation Conference. 
•	Student to describe the weather system and expectation. 
•	Student to describe the complete strategy for the day. 
•	Student to explain and defend why National Playbook route will be issued. 
•	Was the student prepared to provide data to support their decision? 
•	Did Student have backup strategy to manage volume concerns? 

The following are the field facilities comments during the implementation conference: 

ZFW – We agree with the DFW_VKTRY playbook. 
ZAB – What mile in trail does ZFW need? We will have to pass back to ZLA and ZDV. 
ZLA – No concerns. 
ZOA – No concerns. 
ZDV – We do not want two feeds from ZLC for SLC departure. 
ZLC – No issues. 
ZSE – No issues.
"""),

     ("""
     Generate a severe weather training scenario for ZAU/ORD arrivals involving a conflict between meteorologist forecasts. 
     ZAU weather should forecast area growth along the Great Lakes, while the DCC meteorologist predicts diminishing coverage. 
     The scenario should offer two paths: a tactical approach if deviations are minimal, or the implementation of an ORD regional playbook (e.g., CAN-KEMPA-WEST-2 or ORD_EAST_3) if the weather intensifies. 
     Include scripted 'controlling the conference' techniques for the student to practice. 
     Throughout the script, there should be guidelines of the types of questions the student should ask or information they should provide at each key part of the scenario, including engagements with stakeholders to convey weather information and convey plans of action.
     """, 
"""
Training Script:
***Expected Outcome: No TMI’s with possible tactical moves.*** 
 
Set the Stage:  
The student will receive a call from ZAU at 1030z.  
 
ZAU: “The WYNDE arrivals are starting to deviate south into the VEECK 
arrivals. We need to close WYNDE and move all aircraft to FYTTE 
arrival.” 
 
The expectation is that the student ask clarifying questions to evaluate: 
***While the student is asking questions they should be pulling up their ORD TSDs.*** 
 
1.	Are you still getting through on the WYNDE arrival? 
***Instructor can guide the scenario in the direction needed.*** 
 
a)	Instructor response: No 
Student: Advise ZAU that you are moving 45 minutes of demand to allow time for further evaluation. 
 
b)	Instructor response: Yes 
Student: Advise ZAU that you will evaluate the situation and call back shortly. 
  
2.	Have you talked to your meteorologist? 
***Instructor can guide the scenario in the direction needed.*** 
 
a)	Instructor response: No 
Student: Get a briefing from you meteorologist and I will get one from mine. Call you back shortly.  
 
b)	Instructor response: Yes 
Student:  What did he say? 
Instructor response: “My meteorologist is forecasting the area along the great lakes to fill in with medium areas and develop north and south.” 
 
***This ZAU forecast will create conflicting forecast from the meteorologist later in the scenario.***  
3.	How many aircraft have deviated? 
***Instructor can guide the scenario in the direction needed.*** 
  
a)	Instructor response: 1 
Student: Ok, let’s see what the next aircraft does.  
 
b)	Instructor response: 5 
Student: Ok, Let me evaluate the situation. Call you back shortly. 
 
The expectation is the student request a weather briefing from the meteorologist for the ZAU area (Handout #1A).

***Hand student Handout #1 of TCF.***
***Advise student that this is a representation of the current weather.***

Meteorologist briefing:  
 
The area along the east side of the great lakes is moving east. Expect low end sparse coverage with lots of gaps. The system will diminish rapidly over the next hour or so.   
 
If ZAU had received weather briefing from above, the expectation is the student request the meteorologist to call ZAU meteorologist to clarify the forecast due to the discrepancy. 

***The expected student outcome is no TMI’s with possible tactical moves.*** 
 
Student Call back to ZAU: 
 
Instructor: Look for the student to prepare for the conversation 
•	Be able to describe the expected forecast.  
•	Have number of aircraft impacted. 
•	Have a plan for tactical moves. 
•	Have a backup plan if the forecast changes. 
 
Instructor: During the conversation, look for correct articulation of the plan. 
 
Student should identify their self. 
	 	(Good morning, this is [Name] in severe weather) 
Student should ask for the arrivals person. 
Student should provide very short description of impacts.  
(This call is in reference WYNDE arrival impacts) 
 	Student should describe the weather forecast in detail. 
(I received a briefing from my meteorologist and he called your meteorologist so we will be on the same page. Did you get an updated weather forecast? The weather system is at its maximum development and will continue to diminish over the next hour. It is forecasted to be low end sparse coverage with many gaps.) 
 	Student should provide number of aircraft impacted over time period.
(After evaluation, I am showing 5 aircraft in the next hour over the WYNDE arrival gate. 2 are airborne and 3 are departing in the back half of the hour.) 
 	Student should describe the plan.
(With that information, the plan is to let the traffic deviate for the next hour. We can tactically move traffic south to the VEECK arrival to keep them away from the impacted area if that is needed. I know the VEECK arrival is a busy arrival, but we are only talking 5 aircraft and the expectation is they will deviate on the WYNDE arrival. I will continue to monitor the weather and if the forecast changes we will revisit possible initiatives.)  
 	Student should ask ZAU  
(“Do you have any questions or concerns.”)  
***This statement is very important to the conversation. We need to come across as confident that our plan will work. We are not asking permission. This is a technique to control the conversation. We will answer any question and address any concerns. We will reevaluate our plan if given additional information that was not considered.*** 
 
Instructor: Monitor for… 
•	Controlling the conference. 
•	Presenting the plan in a logical order. 
•	Providing all information needed. 
 
LAB_ORD_Scenario B 
 
***Expected Outcome is implementation of playbook route.*** 

***Hand student Handout #2 of TCF.***
***TCF handed to student prior to scenario start to allow them start evaluation of impacts. Allow student about 1 minute before the call comes in from ZAU.***


Set the Stage:
The student will receive a call from ZAU at 1615z.

ZAU: “The WYNDE arrivals are starting to deviate south into the VEECK 
Arrivals. Our meteorologist is forecasting medium pockets along the east side of ORD. We need to close WYNDE and move all the aircraft to FYTTE arrival.” 
 
The expectation is that the student ask clarifying questions to evaluate: 
 
***While the student is asking questions they should be pulling up their ORD TSDs.*** ***During this scenario, we do not need as many clarifying question due to the TCF forecast justifying possible TMIs.***  
 
1. Are you still getting through on the WYNDE arrival? 
***Instructor can guide the scenario in the direction needed.*** 
 
a)	Instructor response: No 
Student: Advise ZAU that you are moving 45 minutes of demand to allow time for further evaluation. 
 
b)	Instructor response: Yes 
Student: Advise ZAU that you will evaluate the situation and call back shortly. 
 
 
The student should request a weather briefing from the meteorologist for the ZAU area. (Handout #2B) 
 
Meteorologist briefing:  
 
The area along the east side of the great lakes is moving east. I agree with the area coverage and intensity forecasted on the TCF. The area of medium coverage will grow and develop in intensity through the 19z hour. 1945z - 2000z, the system will start to decay and by 21z coverage will be sparse.   
 
***The expected outcome is an ORD regional route.*** 
 
The student should start developing a plan 
•	Determine impact time. 
•	Evaluate traffic being impacted. 
•	Determine which playbook will be used. 
•	Evaluate volume on new arrival fix for possible fix balancing. 
•	Build, park and share route with ZAU.
Instructor: look for data based decisions. 
 
Example of Possible playbook outcomes: 
 
1.	ZBW/ZNY/CANADA_TO_ORD 
(Based on CAN-KEMPA-WEST-2 playbook using option #1, keeping traffic on the WYNDE arrival but on the back side of the weather system) 
 
ZDC_TO_ORD 
(Based on ORD_EAST_3 playbook modified, either use MOL or VXV route line based on how far you need to push traffic) 
 
2.	ZBW/ZNY/CANADA_TO_ORD 
(Based on ORD_EAST_1 modified playbook, EWR/LGA over WOZEE and JFK over NOVON) 

ZDC_TO_ORD 
(Based on ORD_EAST_3 playbook modified, either use MOL or VXV route line based on how far you need to push traffic) 
 
3.	ORD_OXI_ROYKO_PARTIAL 
(Use the north east route lines) 
 
***These are just examples, there are many different routes that could be used.*** 
 
 
Student Call back to ZAU: 
 
Instructor: Look for the student to prepare for the conversation.
•	Be able to describe the expected forecast.
•	Have number of aircraft included on playbook along with hourly counts. 
•	Have a backup plan if the forecast changes. 
 
Instructor: during the conversation look for correct articulation of the plan.
 
Student should identify their self. 
	 	(Good afternoon, this is [Name] in severe weather.) 
Student should ask for the arrivals person.
Student should provide very short description of impacts.  
(This call is in reference WYNDE arrival impacts.) 
 	Student should describe the weather forecast in detail. 
(I spoke with the meteorologist. The weather system is expect to extend from east of TVC to south of ROD. The areas of medium coverage will grow and develop in intensity through the 19z hour and then diminish to sparse coverage by 20z.) 
 	Student should provide number of aircraft impacted over time period. 
(After evaluation, I am showing 22 aircraft over the next 3 hours over the 
WYNDE arrival gate. 3 are airborne with 19 still on the ground.) 
 	 
Student should describe the plan 
4.	(I have modeled a ORD_OXI_ROYKO_PARTIAL and parked/shared on 
the TSD. You can pull up the route if you want to see it. Basically, I am taking BWI/IAD/DCA/ZNY/ZBW/Canada to the north side of the weather system. FNT is a little close to the weather system and we may need to modify it north of FNT based on how the weather sets up. There were only 3 aircraft departing tobacco roads so we are going to let them pick their way through the weather. The playbook route will be departure based and run from current time to 19z. Aircraft departing at 19z will not get to the constrained area until 20z or later, which is when the system will diminish to sparse coverage.)  
 	
	Student should ask ZAU:  
(“This plan should provide us with a workable solution, do you have any questions or concerns?”)  
***This statement is very important to the conversation. We need to come across as confident that our plan will work. We are not asking permission. This is a technique to control the conversation. We will answer any question and address any concerns. We will reevaluate our plan if given additional information that was not considered.*** 
 
Instructor: Monitor for…
•	Controlling the conference.
•	Presenting the plan in a logical order.
•	Providing all information needed.

End Scenario
"""),

     ("""
     Create a comprehensive 'Day in the NAS' severe weather scenario for a full 0800Z–1600Z shift. 
     The simulation should revolve around three progressive TCF runs (07z, 09z, and 15z) showing weather development from northern Texas to the Tennessee/West Virginia boundary. 
     The student must develop a changing strategy throughout the day: initially requiring no TMIs, then considering TRANSCON routes, and finally implementing a suite of regional and Transcon plays (e.g., CAN_NOTAP_EAST_1, PXV_PARTIAL) by 15Z to accommodate West Coast departures. 
     Provide a checklist of shift-start tasks and meteorologist briefing scripts for each TCF run.
     """, 
"""
Severe Weather Scripted Simulation Example 3:  LAB_Day_in_The_NAS_Scenario 

Instructor Severe Weather Training Simulation 
 
LAB_Day_in_The_NAS_Scenario 
 
***Expected Outcome Strategy Development and Implementation for the day*** 
 
Set the Stage:  
The student will start their shift at 0800Z.  
 
The expectation is the student follows the suggested opening check: 
 
•	Receive briefing from NTMO or NOM 
•	Open SVRWX NTML 
•	Open IO log and combine to SVRWX NTML 
•	Check WX Models, then receive WX Briefing 
•	Check SVRWX Updates for any carryover info 
•	Check CEDAR  
•	Check Advisory Database for active advisories 
•	Verify reroute monitor functioning for active routes 
•	Check system impact reports (SIR) 
•	Set up right screen with relevant FSM Data 
•	Display weather data on the left screen 
•	Verify AFP FEA’s are running, if AFP’s are possible 
•	Send Caribbean email 
 
0800z: ***Hand student 07z run of TCF handout*** 
07z TCF Run: 

08z Meteorologist briefing:  
 
Small area in northern Texas of high confident sparse coverage moving north east. This system is forecast to remain throughout the morning with a possibility of medium coverage later. Some of the weather products are showing convective possibilities across the mid-west later this afternoon. We will get better information when the weather sounding comes in.  
 
The student will develop basic strategy to manage the NAS. 
  
Instructor will have the student:  
•	Describe TRANSCON strategy and justify. 
***Expectations are TRANSCON routes not needed.*** 
•	Describe Regional route strategy and justify. 
***Expectations are regional routes are not needed.*** 
•	Describe TMI’s needed and implementation triggers. 
***Tactical reroutes will be used if warranted based on field facility request.*** 
***Deviations are expected.*** 
 
______________________________________________________________________ 
 
Possible Strategy example: 
 
EAST TRANSCON 
•	No TRANSCON need, we will continue to monitor weather development  
WEST TRANSCON 
•	No TRANSCON need, we will continue to monitor weather development  
REGIONAL ROUTES 
•	No regional routes need, minor deviations and tactical moves possible 
______________________________________________________________________ 


1000z: ***Hand student 09z run of TCF handout*** 

10z Meteorologist briefing:  
 
No changes in Small area in northern Texas. We have added an area on the western Tennessee / West Virginia boundary of high confident sparse coverage moving east, there is a lot of instability in this region. I tried to convince the chat room to extent and elongate this area. I am expecting this system to extend north and south on the next TCF run. We are also watching the instability along the Appalachians.  
 
***Student should key into the instability and question the growth of the system along the western Tennessee / West Virginia boundary. This system could become problematic based on positioning and growth.*** 
  
The student may adjust their strategy based on the updated information.  
  
Instructor will have the student:  
•	Describe TRANSCON strategy and justify. 
***Expectations are consideration of possible TRANSCON routes.*** 
***need more information to determine market groupings***

Instructor Question: Based on current timing, if weather extends north and south, what TRANSCON bank will be impacted? ***West and possibly late east bank.***
 
•	Describe Regional route strategy and justify. 
***Expectations are consideration of possible regional routes.*** 
***ZMA/ZJX/ZTL to ORD/MDW possible.*** 
 
•	Describe TMI’s needed and implementation triggers. 
***Tactical reroutes will be used if warranted based on field facility request.*** 
***Deviations are expected.*** 
***TRANSCON routes will have to be out by 13z to catch west coast departures.*** 
***Regional route will be implemented when the weather develops.*** 
 
______________________________________________________________________ 
 	 
Possible Strategy example: 
 
EAST TRANSCON 
•	No TRANSCON needed at this point. There are concerns with the instability in the region. Monitor weather forecast closely for possibility of TRANSCON. 
WEST TRANSCON 
•	No TRANSCON needed at this point. There are concerns with the instability in the region. Monitor weather forecast closely for possibility of TRANSCON. 
REGIONAL ROUTES 
•	ORD_OXI_ROYKO_PARTIAL  - ZMA/ZJX/ZTL TO ORD/MDW :  possible 
 
______________________________________________________________________ 


1200Z: ***Hand student 11z run of TCF handout*** 
 
11z TCF Run 

12z Meteorologist briefing:  
 
Small area in northern Texas continues to move east and remain intact. The weather system along western Tennessee / West Virginia was extended north and south. There is a lot of instability associated with this system. As the sounding data is incorporated, I would not be surprised if areas of medium coverage are added and the polygon extended even further north and south. Small area along the western Appalachians, not a lot of instability associated with this. This system is on the low end of sparse criteria and is east of the front.     
 
***Student should question “areas of medium coverage”.*** 
•	Where do you see the possibility for areas of medium coverage? 
•	When will they start to develop? 
•	How long will they last? 
•	Is this system at the high end of sparse coverage or low?
 
The student is expected to finalize their strategy for the day and be prepared to present to the group.  

***Expectations are TRANSCON routes for west to east, possible late TRANSCON east to west, regional routes in and out of ORD.*** 

***Expect the student to have playbooks in mind based on their experience.*** 
 
______________________________________________________________________ 
 
	 	 	Possible Strategy example: 
  
EAST TRANSCON 
•	GRB_PARTIAL              -  PACNW/ZDV/ZMP TO EWR/LGA : possible 
•	PXV_PARTIAL               - ZLA/ZAB/ZHU/ZFW TO EWR/LGA/JFK : possible 
•	CEW_PARTIAL              - ZLA/ZAB/ZFW/ZHU TO DC METS :possible 
WEST TRANSCON 
•	KNKER2_PARTIAL        - ZNY TO ZLA/ZAB/SFO : possible 
•	ELP_PARTIAL                - ZDC TO ZLA/ZAB/SFO : possible 
 
CAN ROUTES 
Need for CAN routes are questionable at this point 
 
REGIONAL ROUTES 
•	ORD_OXI_ROYKO_PARTIAL  - ZMA/ZJX/ZTL TO ORD/MDW : possible 
 
______________________________________________________________________ 
 
Instructor should act as the NTMO and hold a group huddle to discuss the strategies. 

***Incorporate at least two other people as specialist to the conversation.*** 
 
NTMO: “Looks like sparse coverage so far, don’t see a need for TRANSCON’s, maybe some regional route are possible. What do you see? We will start with (Student’s name)” 
 
Student: ***Student describes strategy and justifies.*** 
	            	          ***Strategy should include possible playbooks and market groups.*** 
 
Specialist 1 & 2: ***This part is very dynamic, specialist will have to adjust their 
       	       questions based on the strategy of the student.*** 

***Have one specialist lean toward AFP’s and the other lean toward no TRANSCON, just regional routes.*** 
 
Typical ideas that could be used for discussion:  
1.	Did we consider AFP’s? 
2.	Where are the customers filing? 
3.	Do we need CAN routes? 
4.	Are there any volume concerns based on the traffic that is being moved? 
5.	Do we need additional routes to manage volume? 
6.	Is it possible to let the first bank fly through and deviate without structure? 
7.	Could be let the first couple of hours of the bank fly through and catch the back end of the bank only based on the weather development? 
8.	It there any uncertainty in the weather forecast? 
 
Once all ideas have been explored, the group finalizes the strategy for the day. This strategy will be very specific including departure point and destination to be include with each play. Student should be able to articulate the purpose and describe the need for each of the TMI’s that are going to be implemented.  
 
The NTMO (instructor) will assign task to the specialist to start building and parking needed structure. 

***This setup allows the instructor to select the task that he wants the student to demonstrate (building Regional routes, TRANSCON routes, coordinating CAN Routes…)*** 
 
______________________________________________________________________ 
 
Possible Strategy example: 
  
EAST TRANSCON 
•	CAN_NOTAP_EAST_1  -  PACNW/ZDV TO ZBW/JFK 
•	GRB_PARTIAL              -  PACNW/ZDV/ZMP TO EWR/LGA 
•	PXV_PARTIAL               - ZLA/ZAB/ZHU/ZFW TO EWR/LGA/JFK 
•	CEW_PARTIAL              - ZLA/ZAB/ZFW/ZHU TO DC METS 
WEST TRANSCON 
•	CAN_SSM_WEST_2      - JFK/ZBW TO PACNW/DEN 
•	KNKER2_PARTIAL        - ZNY TO ZLA/ZAB/SFO 
•	ELP_PARTIAL                - ZDC TO ZLA/ZAB/SFO 
REGIONAL ROUTES 
•	ORD_OXI_ROYKO_PARTIAL  - ZMA/ZJX/ZTL TO ORD/MDW 
 
______________________________________________________________________ 
 The student is expected to complete the task assigned.  
 
Critical Decision Point 
 
***It is at this point we need to make a decision about the TRANSCON routes, do we implement or wait for next weather update?*** 

***Based on the current information, the expectation is to wait for the next weather update and let the first hour of west coast departures off on normal routes.*** 

***Traffic impacting the 19z panel will depart west coast around 16z so we have time to get updated weather information.*** 
 
 
1400z: ***Hand student 13z run of TCF handout*** 

14z Meteorologist briefing:  
 
Small area of sparse coverage along the east coast and along the western boundary of ZDC, there will be isolated convective activity in these areas starting 19z and later. All three panels show areas of sparse coverage on the east coast of Georgia and Florida, this is sea breeze activity and it will continue to develop and diminish until sun set when we lose the heating. The area along the western side of Tennessee / West Virginia continue to expand and develop through all three panels, there is still a lot of instability associated with this area, I think the 19z panel is a little over done, it will be closer to 20z before we see the expanded development, the area of medium cover in western Texas is under defined, I tried to have a larger polygon drawn, during our chat session, extending further east. Still evaluating medium coverage areas on the norther side and along the Appalachians. Medium coverage areas north of the Texas Pan Handle will develop rapidly, development will start around 2130z and meet medium criteria by 2200z.  
 
  
 ***Student should question areas of sparse coverage along the east coast and western ZDC, small thunderstorms can be very impactful in this area.*** 
•	Low end sparse or high end sparse? 
•	When will they start to develop? 
•	How long will they last? 
•	How high are the tops? 
 
***Student should question the possibility of medium coverage east of Texas and the potential medium coverage areas on the northern side of system.*** 
•	Will the area in western Texas extend further north? 
•	How high are the tops? 
•	Where do you see the medium coverage areas developing on the north side? 

***Student should question the rapid development area north of the pan handle.***
•	How confident are you with the location? 
•	How high are the tops? 
 
 
Critical Decision Point 
 
Student will make changes to the strategy and start the implementation process for the TRANSCON routes that are needed based on the updated forecast.  
 	
	***West coast departures are already starting to get airborne.*** 
***Student should develop triggers for implementation allowing 45 min to 1 hour before departure time for customers to prepare.*** 

***The west coast departure that will impact the 19z TCF panel will depart at 16z. Routes will have to be out by 15z to allow customers preparation time.*** 

***With the extended polygons in the new weather update and the uncertainty of weather development, CAN routes will probably be needed.*** 
______________________________________________________________________ 

Possible Strategy example:
  
EAST TRANSCON 
•	CAN_NOTAP_EAST_1  -  PACNW/ZDV TO ZBW/JFK 
•	GRB_PARTIAL              -  PACNW/ZDV/ZMP TO EWR/LGA 
•	PXV_PARTIAL               - ZLA/ZAB/ZHU/ZFW TO EWR/LGA/JFK 
•	CEW_PARTIAL              - ZLA/ZAB/ZFW/ZHU TO DC METS 
WEST TRANSCON 
•	CAN_SSM_WEST_2      - JFK/ZBW TO PACNW/DEN 
•	KNKER2_PARTIAL        - ZNY TO ZLA/ZAB/SFO 
•	ELP_PARTIAL                - ZDC TO ZLA/ZAB/SFO 
REGIONAL ROUTES 
•	ORD_OXI_ROYKO_PARTIAL - ZMA/ZJX/ZTL TO ORD/MDW 
 
______________________________________________________________________ 

1600Z***Hand student 15z run of TCF handout*** 

15z TCF Run

16z Meteorologist briefing:  
 
Sparse coverage areas along the east coast will remain isolated and diminish after 23z. Sparse coverage from ORD to ATL extending west to Texas, 21z/23z panel show medium coverage in ZTL and ZID airspace, based on other weather models you can expect isolated medium coverage across the region. Medium coverage was added to the system in the Midwest extending from Texas to MSP, the areas of medium coverage are well defined, expect these areas to be expanded on the next TCF run.  
 
This is the end of the shift: 
Route structure should be implemented or parked waiting. Student should brief the eve shift as they arrive. 
 
Instructor should make sure the student:
•	Uses the check list. 
•	Describes the weather system completely. 
•	Describes the strategy for the afternoon to include:  
•	Playbooks used 
•	Market groups include on each play 
•	Any concerns with volume  
•	Any plays that are parked waiting for implementation trigger 
•	Any tactical approaches 
•	Any field facility concerns  
•	Any adjustment that will need to be made later 
•	Describes any conflicts during implementation to include reason for resolution.
""")

]